zextras/carbonio-mailbox

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- provide the correct command to unset the userPassword
> chore: provide command in error message

- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/mail/message/GetPreviewRequest.java
- soap/src/java/com/zimbra/soap/mail/message/GetPreviewResponse.java
- store/src/java-test/com/zimbra/cs/service/mail/GetPreviewTest.java
- store/src/java/com/zimbra/cs/service/mail/GetPreview.java
- store/src/java/com/zimbra/cs/service/mail/MailService.java
- enables generate previews for mail attachment using Carbonio previewer service based on passed parameters.
> feat(SOAP): [CO-185] preview service SOAP endpoint

- store/src/java/com/zimbra/cs/service/account/Auth.java
- fixes Auth response when request ask the 
format js(JSON)
> fix: Auth response in json format

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- store-conf/conf/rights/rights-adminconsole.xml
- store-conf/conf/rights/rights-domainadmin.xml
- store/conf/attrs/attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/ToXML.java
- store/src/java/com/zimbra/cs/service/admin/ModifyCos.java
- support: COS/Account hierarchy for additional LDAP Attributes 
- fix: prevent common words in the account password string
> fix:[CO-236] COS/Account LDAP attribute

- packages/appserver-service/PKGBUILD
- packages/appserver-service/carbonio-mailbox
changes to allow mailboxd, executed by user zextras, to access Key-Value store in Consul
> Mailboxd access consul kv

- packages/appserver-service/carbonio-mailbox
> fix: CO-297 - fix access privileges on token file to 'carbonio-mailbox' group

- packages/appserver-service/PKGBUILD
> chore: update postinstall message

- store/src/java-test/com/zimbra/cs/service/MockHttpServletResponse.java
- store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
- store/src/java/com/zimbra/cs/service/PreviewServlet.java
key change:
- https://github.com/Zextras/carbonio-mailbox/pull/51/files#diff-af5013b1979149a28c4275ed38534e3d75c5a947a7253b54973229ab94ea774dR356
- https://github.com/Zextras/carbonio-mailbox/pull/51/files#diff-d616bfd8f0383718e7c8a758c940f71d19360e468411efe19b21dc6229b8f055R122
> [CO-300] proxy 5xx errors to 404 in previewServlet

- Jenkinsfile
- build-common.xml
- build.xml
- jacoco-common.xml
- junit-common.xml
Add Junit report and JaCoCo report coverage
- added **jacoco-common.xml** to load and download JaCoCo plugin
- added **junit-common.xml** to load and download Junit plugin
- **removed old Emma plugin** coverage build-common.xml
- **wrapped junit tests with jacoco** agent in build-common.xml
- add ant target to merge multiproject JaCoCo coverage
- Jenkinsfile: jacoco and junit publish reports 
- Jenkinsfile: run all tests (unit & IT) when TEST param enabled
> chore: [Co-303] enable tests with coverage in CI

- build.xml
Fixes NaN Code Coverage report
> fix: JaCoCo merge report classes

- store/build.xml
- store/ivy.xml
- store/src/java/org/apache/mina/transport/socket/nio/ZimbraSocketAcceptor.java
Updates apache mina-core to 2.1.6
> chore: [CO-357] update mina-core to 2.1.6

- Jenkinsfile
- common/src/java-test/com/zimbra/common/soap/ElementTest.java
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponseTest.java
- soap/src/java-test/com/zimbra/soap/account/JaxbToElementTest.java
- soap/src/java-test/com/zimbra/soap/admin/DumpSessionsTest.java
- soap/src/java-test/com/zimbra/soap/admin/GetAllConfigTest.java
- soap/src/java-test/com/zimbra/soap/admin/GetServerTest.java
- soap/src/java-test/com/zimbra/soap/admin/MailQueueActionTest.java
- soap/src/java-test/com/zimbra/soap/mail/GetFolderTest.java
- soap/src/java-test/com/zimbra/soap/mail/SyncResponseTest.java
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java-test/com/zimbra/cs/imap/LocalImapMailboxStoreTest.java
- store/src/java-test/com/zimbra/cs/imap/MemcachedImapCacheTest.java
- store/src/java-test/com/zimbra/cs/index/ZimbraQueryTest.java
- store/src/java-test/com/zimbra/cs/index/analysis/UniversalAnalyzerTest.java
- store/src/java-test/com/zimbra/cs/mailbox/MailboxTest.java
- store/src/java-test/com/zimbra/cs/mailbox/MessageTest.java
- store/src/java-test/com/zimbra/cs/service/FeedManagerTest.java
- store/src/java-test/com/zimbra/cs/service/RecoverAccountTest.java
- store/src/java-test/com/zimbra/cs/service/mail/ParseMimeMessageTest.java
- store/src/java-test/com/zimbra/cs/service/mail/SearchTest.java
Always run tests for every commit.
This will allow us to better track test status and regression.
Also **many tests** (~40) **were failing because of some missing xml files**, some not (~10).
In order to track new changes **I propose to remove them** and **focus on newly added and regressions**, until we add required xml files for owasp tests, etc.
**This translates to: CI must be always green**
* Always run tests (Jenkinsfile)
* Ignore failing tests from main branch
* Fix failing test after (49da605ef57d2369413a939477594ecfbf70d067) (checks on null instead of emptySet)
> chore: always run tests

- store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
- store/src/java/com/zimbra/cs/service/PreviewServlet.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
**Key changes:** 
- Preview servlet now can preview attachments that are part of shared email folders
> feat: [CO-359] add ability to preview attachments in shared mailbox folders

- store/build.xml
- store/ivy.xml
- store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
- store/src/java/com/zimbra/cs/service/PreviewServlet.java
**Key changes:**
- Preview SDK version bumped from 0.2.3 to 0.2.4
- Preview servlet now can preview documents
- more unit tests
> feat: [CO=358] support document preview

- Jenkinsfile
**Key changes:** 
- skip test with coverage step if parameter(SKIP_TEST_WITH_COVERAGE) is set checked or set to true
- file formatting
> chore: new pipeline parameter to skip tests

- Jenkinsfile
- fix space caused by groovy formater in one of ant task
> fix: ant build step name

- packages/appserver-service/carbonio-mailbox
- update acl rule to add read policy for carbonio-auth service
> chore: [CO-370] add consul KV read policy for carbonio-auth

- store/conf/attrs/attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
* Regenerate attrs.xml based codebase
[CO-338]
> feat: zimbraAuthFallbackToLocal is by default set to TRUE

- common/src/java/com/zimbra/common/soap/CertMgrConstants.java
- soap/src/java/com/zimbra/soap/admin/message/VerifyCertKeyRequest.java
Add ca optional attribute to VerifyCertKeyRequest.
Needed to implement VerifyCertKey on repo: https://github.com/Zextras/carbonio-certificate-manager-store
> feat: [CO-402] add ca attribute to verifycertkeyrequest

- Jenkinsfile
- build-common.xml
- build-ivysettings.xml
- build.xml
This PR is a proposal to deploy mailbox artifacts on a maven snapshot repo when in branch devel.
It will allow early stage development on packages that have mailbox as dependencies.
> chore: [CO-408] maven deploy snapshot on devel

- Jenkinsfile
- Jenkinsfile.nightly
- README.md
- packages/appserver-conf/PKGBUILD
- packages/appserver-service/PKGBUILD
- packages/appserver-war/PKGBUILD
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-db/PKGBUILD
- packages/common-appserver-docs/PKGBUILD
- packages/common-appserver-native-lib/PKGBUILD
- packages/common-core-jar/PKGBUILD
Bump for 22.11.0 + 4.0.17 packages
> chore: bump next version

- store/src/java/com/zimbra/cs/service/mail/CalendarRequest.java
Aim: fix the OnBehalfOfRequest check.
> fix:[CO-407] correctly check delegated account requests

- Jenkinsfile
- Jenkinsfile.nightly
- README.md
- build-common.xml
- build-ivysettings.xml
- build.xml
- client/src/java/com/zimbra/client/ZDomain.java
- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- packages/appserver-conf/PKGBUILD
- packages/appserver-service/PKGBUILD
- packages/appserver-war/PKGBUILD
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-db/PKGBUILD
- packages/common-appserver-docs/PKGBUILD
- packages/common-appserver-native-lib/PKGBUILD
- packages/common-core-jar/PKGBUILD
- store/conf/attrs/attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/service/PreviewServlet.java
- store/src/java/com/zimbra/cs/service/admin/GetDomainInfo.java
- store/src/java/com/zimbra/cs/service/mail/CalendarRequest.java
Main changes:
- Add attributes for white-labeling and theme management
Other changes:
-  CO-367 (add carbonioMeshCredentials) code generation
Note: this PR also contain other changes in commit section due to rebasing, please ignore them.
> feat: [CO-330] add white labeling attributes plus fixups

- Jenkinsfile
Publish packages to devel once in devel.
> chore(Jenkinsfile): add devel repository

- catalog-info.yaml
Having backstage catalog in main branch will lead to project auto-discover.
> chore: add backstage

- common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/attrs.xml
- store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java
Add global multi-attribute carbonioClamAVDatabaseCustomURL for freshclam.
Other needed PRs: 
- https://github.com/Zextras/carbonio-ldap-utilities/pull/18
- https://github.com/Zextras/carbonio-freshclam/pull/2
> feat: [CO-467] add carbonioClamAVDatabaseCustomURL global multi-attr

- ant-build-common.xml
- soap/ant-generate-soap-docs.xml
- soap/pom.xml
- soap/templates/api-reference/stylesheet.css
- store/ant-store.xml
~~-**fix: generate, package buildinfo class**~~
~~- Now generate and package buildinfo class for soap module in respective mvn phases.~~ (NOT REQUIRED, using version property defined by ant task)
- **fix: set build version from ant-build-common's target**
- This also accomodate the soap docs generator to have correct build info version in the generated files
- **fix: properly set anchor scroll offset**
-  Now offsets html anchors according to the height of fixed header
> chore: soap docs style & buildinfo for soap module

- CHANGELOG.md
This is the CHANGELOG generated locally using release-it.
> chore: add proper release-it CHANGELOG.md

- ant-build-common.xml
- pom.xml
> chore: start 23.3.0 devel cycle

- store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
* ProxyConfGen remove docs.common expansion
* ProxyConfGen remove docs.upstream expansion
> feat: [CO-559] remove docs common template expansion

- pom.xml
> chore: bump 23.3.0

- store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
- Expand chats messaging xmpp template
- Delete old chats messaging xmpp templates
This is related to this PR: https://github.com/Zextras/carbonio-nginx-conf/pull/49
> chore: [CHATS-560] Chats messaging xmpp ProxyConfGen

- common/src/main/java/com/zimbra/common/calendar/ZCalendar.java
- common/src/main/java/com/zimbra/common/calendar/ZoneInfo2iCalendar.java
- store/src/main/java/com/zimbra/cs/datasource/CalDavDataImport.java
- store/src/main/java/com/zimbra/cs/dav/resource/CalendarObject.java
- store/src/main/java/com/zimbra/cs/fb/FreeBusy.java
- store/src/main/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarMailSender.java
- store/src/test/java/com/zimbra/cs/service/mail/bug-69862-invite.txt
- store/src/test/resources/com/zimbra/cs/imap/calendar-bounce
- store/src/test/resources/com/zimbra/cs/mailbox/calendar/Calendar_ChangeMeetingRequest_WO_Rsvp.txt
- store/src/test/resources/com/zimbra/cs/mailbox/calendar/Calendar_NewMeetingRequest_RsvpFalse.txt
- store/src/test/resources/com/zimbra/cs/mailbox/calendar/Calendar_NewMeetingRequest_RsvpTrue.txt
- store/src/test/resources/timezones-test.ics
> chore: [CO-546] Rename ZimbraProdId into CarbonioProdId for events

- ant-build-common.xml
- pom.xml
> chore: 23.5.0-SNAPSHOT

- store-conf/conf/antisamy.xml
- store-conf/conf/owasp_policy.xml
- store/ant-store.xml
- store/src/test/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
> chore: fix OwaspHtmlSanitizerTest by providing missing files

- store/src/main/java/com/zimbra/cs/account/callback/ChildAccount.java
Adding back because AttributeManager produces a nasty warning when using zmprov cli
> fix(CO-744): add back ChildAccount

- store/src/main/java/com/zimbra/cs/account/callback/ChildAccount.java
* fix(CO-744): add back ChildAccount
* chore: add deprecated
> chore: main-to-devel

- packages/appserver-service/carbonio-mailbox.hcl
- to allow scanner extension work in multi server environment
> feat: [CO-762] Add carbonio-clamav upstream

- common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java
- store-conf/conf/rights/rights-domainadmin.xml
- store/conf/attrs/attrs.xml
- store/ldap/src/updates/attrs/1690904855.json
- store/ldap/src/updates/attrs/ReadMe.md
- store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java
- Added LDAP attributes in attrs.xml and rights-domainadmin.xml
- Added JSON configuration for LDAP update script
> feat: [CO-784] add documentation URL attributes

- CHANGELOG.md
- packages/appserver-conf/PKGBUILD
- packages/appserver-service/PKGBUILD
- packages/appserver-store-libs/PKGBUILD
- packages/appserver-war/PKGBUILD
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-db/PKGBUILD
- packages/common-appserver-docs/PKGBUILD
- packages/common-appserver-native-lib/PKGBUILD
- packages/common-core-jar/PKGBUILD
- packages/common-core-libs/PKGBUILD
> chore: release 23.9.0/4.8.1

- store/src/main/java/com/zimbra/cs/dav/resource/CalendarCollection.java
- fix regression from 0a265ebd7ba819ab3d04e4ef41dd7db07113870e
Changes were cherry-picked from commit 647f2b6dbc96004b223537b5a61ccb4aaa650e69 in branch fix/CO-822
which includes also tests for this behavior.
> fix: allow Appointment creation from CalDAV

- pom.xml
> chore: remove snapshot

- common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/attrs.xml
- store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java
- Deprecated all the CSRF-related LDAP attributes
> chore: [CO-818] deprecated CSRF-related LDAP-attributes

- common/src/main/java/com/zimbra/common/util/LogFactory.java
- common/src/test/java/com/zimbra/common/util/LogFactoryTest.java
- store/src/main/java/com/zimbra/cs/service/admin/AddAccountLogger.java
- store/src/main/java/com/zimbra/cs/service/admin/AdminService.java
- store/src/test/java/com/zextras/mailbox/usecase/InMemoryLdapServerTestUtil.java
- store/src/test/java/com/zextras/mailbox/usecase/MailboxTestUtil.java
- store/src/test/java/com/zimbra/cs/service/admin/AddAccountLoggerTest.java
- store/src/test/resources/localconfig-api-test.xml
**What has changed**:
- logger creation starts using logger context
- add AddAccountLoggerTest, LogFactoryTest
ref: CO-842
> fix: log category does not exist

- Jenkinsfile
Refs: [IN-610]
[IN-610]: https://zextras.atlassian.net/browse/IN-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ubuntu 22.04 (jammy jellyfish) support

- pom.xml
- store/src/main/java/com/zimbra/cs/service/PreviewServlet.java
- store/src/test/java/com/zimbra/cs/service/PreviewServletTest.java
**What has changed**
- bump preview-sdk version to 1.0.2
- Added GIF support in PreviewServlet.java
> feat: [CO-779] Use latest Preview SDK

- common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/attrs.xml
- store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/main/java/com/zimbra/cs/account/ZAttrCos.java
> chore: deprecate zimbraFeatureMailEnabled attribute

- store/src/main/java/com/zimbra/cs/service/account/Auth.java
- store/src/test/java/com/zimbra/soap/AuthRequestTest.java
- Auth API now creates regular Auth token with AUTH usages when token is requested using password recovery code.
> feat: [CO-917] generate regular auth token for recover password requests

- store/ant-store.xml
- store/pom.xml
- accidentally removed autogen of these files in: https://github.com/zextras/carbonio-mailbox/pull/392
> fix: generateversions-init.sql and attr-schema

- store/src/test/java/com/zextras/mailbox/domain/usecase/AclServiceTest.java
- store/src/test/java/com/zextras/mailbox/util/MailboxTestUtil.java
- store/src/test/java/com/zimbra/cs/dav/CalDavCreateAppointmentRequestBuilder.java
- store/src/test/java/com/zimbra/cs/dav/CalDavFreeBusyRequestBuilder.java
- store/src/test/java/com/zimbra/cs/dav/service/DavServletTest.java
- store/src/test/java/com/zimbra/cs/service/admin/DeleteAccountTest.java
- store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
Removed static MailboxTestUtil methods in favor of builder classes
> test: remove deprecated test utils methods and use new classes

- store/src/test/java/com/zimbra/cs/mailbox/ContactTest.java
- reason: CI fails randomly because of it
> test: ignore ContactTest#createAutoContact

- carbonio-jetty-libs/pom.xml
- packages/common-appserver-docs/PKGBUILD
- packages/common-core-libs/PKGBUILD
- pom.xml
- store-extra-runtime-dependencies/pom.xml
- spring-*
- w3c sac
- remove install instruction for soap-mobile.txt
- cleanup
> chore: remove unused dependencies

- CHANGELOG.md
release-it was not working for me during we made the 4.12.0 release
> chore: Update changelog 4.12.0

- store/src/test/java/com/zimbra/cs/imap/ImapHandlerTest.java
- better create new account for each test to avoid test affecting each other
> test: ImapHandlerTest create account for each test to avoid side effects

- Makefile
> chore: [CO-942] add initial Makefile to simplify RC

- docker/jetty-run/docker-compose.yml
- docker/jetty-run/docker-jetty-localconfig.xml
- docker/jetty-run/entrypoint-ldap.sh
- image was renamed
- updated checks
- updated hostname to match new one defined during bootstrap
> chore(docker): move from ldap-server to carbonio-ce-directory-server

- store/src/test/java/com/zextras/mailbox/soap/SoapTestSuite.java
- store/src/test/java/com/zimbra/cs/service/admin/FlushCacheTest.java
Added some API tests for FlushCache.java to document the behavior of this API.
> test: [COR-1026] flush cache

- Jenkinsfile.nightly
bring in relevant portion from fb86d689dff05846d2891dbe6a883da78494aea1 from main fixing few merge conflict
> Align main with devel

- packages/appserver-conf/PKGBUILD
- packages/appserver-db/PKGBUILD
- packages/appserver-service/PKGBUILD
- packages/appserver-store-libs/PKGBUILD
- packages/appserver-war/PKGBUILD
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-native-lib/PKGBUILD
- packages/common-core-jar/PKGBUILD
- packages/common-core-libs/PKGBUILD
- packages/directory-server/PKGBUILD
- packages/directory-server/carbonio-directory-server.target
> chore: Align devel with main

- packages/appserver-service/carbonio-appserver.service
This is a QA fix for 24.5.0, need to be back-merged to devel
> fix: systemd: only trigger configd rewrite as pre-start condition

- store/src/test/java/com/zextras/mailbox/util/MailboxTestUtil.java
- store/src/test/java/com/zimbra/cs/db/HSQLDB.java
- store/src/test/java/com/zimbra/cs/mailbox/MailboxTestUtil.java
> refactor: remove zimbraServeDir argument from HSQLDB methods

- store/src/main/java/com/zimbra/cs/service/mail/AutoComplete.java
- store/src/main/java/com/zimbra/cs/service/mail/FullAutoComplete.java
- store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
- This improves the performance of the API call by executing the request locally if the requested account is on local server. This change also prevents the possibility of causing loop in ZimbraQoSFilter in certain conditions(Server configuration and stress see the ticket CO-1074 for full context).
> feat: [CO-1074] avoid SOAP request to perform AutoComplete if requested account is local

- soap/src/main/java/com/zimbra/soap/mail/type/RecoverAccountOperation.java
- store/src/main/java/com/zimbra/cs/service/mail/RecoverAccount.java
- remove sendRecoveryLink operation from RecoverAccount API
> feat: [CO-904] Remove sendRecoveryLink operation from RecoverAccount API

- packages/appserver-db/carbonio-appserver-db.service
- packages/appserver-service/carbonio-appserver.service
- packages/common-appserver-conf/carbonio-milter.service
Refs: IN-701
This is needed in 24.7.0
> chore: systemd: add LimitNOFILE to some systemd units

- packages/directory-server/PKGBUILD
- store/ldap/src/migrations/migrate20240201-AddOpenLDAP25.pl
> chore: add migration for ldap 2.5

- store/src/main/java/com/zextras/mailbox/LikeXmlJettyServer.java
- store/src/test/java/com/zextras/mailbox/MailboxTest.java
chore: move private method user connector near other connector
> test: update MailboxTest

- packages/common-appserver-conf/carbonio-milter.service
> fix: carbonio-milter.service: class not found cause of classpath edits

- Jenkinsfile
- packages/directory-server/PKGBUILD
> feat: add ubuntu 24.04 (ubuntu-noble) support

- pom.xml
This mainly affects configd execution. I tested it on latest devel images. Everything seems to work fine with config generation and configd service.
Closes: CVE-2016-4000, CVE-2013-2027
Refs: IN-763
> chore: update jython to 2.7.4

- Jenkinsfile
> fix: ci: upload rhel packages to devel

- common/src/main/java/com/zimbra/common/localconfig/LC.java
> chore: remove unneeded postjournal references

- carbonio-jetty-libs/pom.xml
- common/pom.xml
- pom.xml
- soap/pom.xml
- store/pom.xml
- store/src/main/java/com/zimbra/cs/service/authenticator/CertUtil.java
- store/src/test/java/com/zimbra/cs/db/HSQLDB.java
Some code changes were required. Notable changes are:
- `URL url = null;` to use non-ambigous function SqlFile (HSQLDB.java) -> hsqldb update
- Conversion for DERUTF8String (CertUtil.java) -> bouncy update
> chore: close some security issues here and there

- pom.xml
- store/src/main/java/com/zimbra/cs/account/ProvUtil.java
- store/src/test/java/com/zimbra/cs/account/ProvUtilTest.java
- `createBulkAccounts` requires password for the created users
- add an error message when there's an argument number mismatch
> CO - 1563 Mailbox security issue : default password hard coded

- .release-it.json
- README.md
- package-lock.json
- package.json
Proposal to add a script to run release-it along with documentation to publish package in RC channel.
Introducing package.json simplifies release-it installation locally.
> chore: release it allow tag

- soap/src/main/java/com/zimbra/soap/account/message/SearchUsersByFeatureRequest.java
- soap/src/main/java/com/zimbra/soap/account/message/SearchUsersByFeatureResponse.java
- store/src/main/java/com/zimbra/cs/service/account/SearchUsersByFeature.java
- store/src/test/java/com/zimbra/cs/service/account/SearchUsersByFeatureTest.java
added:
- offset parameter to the request (limit was already present)
- total and more attributes to the response
> CO-1489: added pagination support to search users by feature

- store/src/main/java/com/zextras/mailbox/MailboxAPIs.java
- it is important to define servlets names, so extension can override them at runtime by providing their own custom implementation
reported the values as they were in web.xml
> fix: add required filters and servlet names

- pom.xml
> chore: close critical Apache MINA Deserialization RCE Vulnerability

- pom.xml
- store/src/main/java/com/zimbra/cs/service/servlet/preview/PreviewHandler.java
- store/src/main/java/com/zimbra/cs/service/servlet/preview/PreviewQueryParameters.java
- store/src/main/java/com/zimbra/cs/service/servlet/preview/Utils.java
- store/src/test/java/com/zimbra/cs/service/servlet/preview/UtilsTest.java
Related PRs: https://github.com/zextras/carbonio-mails-ui/pull/849
> feat: [CO-1954] support lang_tag when calling preview service

- pom.xml
> chore: [IN-868] pom.xml: update com.fasterxml.jackson to 2.12.7.2

- packages/appserver-db/PKGBUILD
- packages/appserver-db/carbonio-appserver-db.service
- packages/appserver-service/PKGBUILD
- packages/appserver-service/carbonio-appserver.service
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-conf/carbonio-milter.service
- packages/directory-server/PKGBUILD
- packages/directory-server/carbonio-directory-server.target
> chore: systemd: enable carbonio.target units hierarchy

- packages/appserver-db/carbonio-appserver-db.service
- packages/appserver-service/carbonio-appserver.service
- packages/common-appserver-conf/PKGBUILD
- packages/common-appserver-conf/carbonio-milter.service
> chore: some enhancements for carbonio.target units hierarchy

- packages/appserver-service/PKGBUILD
- packages/directory-server/PKGBUILD
> chore(PKGBUILD): only disable units on uninstall for rpms

- common/src/main/java/com/zimbra/common/localconfig/LC.java
- docker/standalone/mailbox/Dockerfile
- docker/standalone/mailbox/entrypoint.sh
- docker/standalone/mailbox/localconfig/localconfig.xml
- store/src/main/java/com/zimbra/cs/service/admin/AdminService.java
- store/src/main/java/com/zimbra/cs/service/mail/MailService.java
- store/src/main/java/com/zimbra/cs/service/servlet/preview/Constants.java
- store/src/main/java/com/zimbra/cs/service/servlet/preview/PreviewServlet.java
Added localconfig keys `files_service_url` and `preview_service_url` with defaults.
> chore: allow parameterized files and preview connection from localconfig

- Jenkinsfile
* Migrate from using individual title and descriptionFile parameters
to a consolidated ocLabels structure for Docker image builds.
> chore(ci): update pipeline packaging library to 1.0.1
