zextras/carbonio-mailbox

common/src/java/com/zimbra/common/localconfig/LC.java
Admin console requests locales by SOAP call on mailbox.
Mailbox is loading locales from a directory that is not provided by the admin package.
This is a fix to make mailbox return locales provided by carbonio-appserver-admin-console-war package.
I've done more tests on this. The changes I made should impact only a method that returns a list of Language Codes and that works this way:
* Scans the stated directory and **infer** language codes based on file names. Note that matching file names are only the ones
like AjxMsg, and couple others (see WebClientL10nUtil.java line 60)
Further tests I made:
* Change location of localization client directory to point to admin directory: 
* observe admin languages dropdown is working;
* change language and see admin panel changes languages;
* see also …
=> fix(LC.java): set localized_client_msgs_dir to load locales from admin path

packages/appserver-service/carbonio-mailbox
Naming of user-management service is carbonio-user-management.
With user-management the intention wouldn't work.
=> fix(carbonio-mailbox): user-management to carbonio-user-management

store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
user attribute cannot be part of their password
added new password policy which will prevent users from adding their
personal data in their password string
this policy is enforced by default
=> New Password policy without LDAP attribute

packages/appserver-service/carbonio-mailbox.hcl
* Leave envoy proxy port as default instead of manually assign it
=> fix(carbonio-mailbox.hcl): proxy port as default

packages/appserver-conf/PKGBUILD, packages/appserver-service/PKGBUILD, packages/appserver-war/PKGBUILD
service-discover and pending setups should be carbonio-core dependencies, because shared between multiple components. This also fix some issues on files and folders detection during the postinst phase
Please have a look also [here](https://github.com/Zextras/carbonio-nginx-conf/pull/7)
=> refactor(packages): CO-37: enable multiserver installations

packages/appserver-service/carbonio-mailbox.hcl
Since the previewer service has to be integrated with the mailbox in Carbonio, the carbonio-preview has been added to the carbonio-mailbox.hcl file to allow mailbox to communicate with preview via consul.
=> feat(carbonio-mailbox.hcl): add carbonio-preview (#18)

store/src/java/com/zimbra/cs/util/ProxyConfGen.java
Chats messaging configs for nginx were added to the templates list to allow for expansion
with the proxy restart
=> Included template expansion for messaging configs

soap/src/java/com/zimbra/soap/admin/type/AdminAttrsImpl.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/java/com/zimbra/cs/service/admin/CreateAccount.java
- this avoids forcing the account UUID(zimbraId attribute) while account creation using "zmprov" util and SOAP API
- other little enhancements in LDAP prov
=> chore: prevent passing zimbraId attribute in LDAP & SOAP prov

packages/appserver-service/carbonio-mailbox
Allow Files to access mailbox
###Tests
Tested with pending-setups: allow intention carbonio-files -> carbonio-mailbox is registered
=> chore: add carbonio-files intention to allow access on mailbox

common/src/java-test/com/zimbra/common/util/MockHttpServletResponse.java, common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java, common/src/java/com/zimbra/common/util/SameSiteAttribute.java, common/src/java/com/zimbra/common/util/ZimbraCookie.java, store/src/java/com/zimbra/cs/account/ZimbraAuthToken.java
**SameSiteAttribute** Utility class to set SameSite attribute of the Set-Cookie HTTP response header.
Both `ZM_AUTH_TOKEN` and `ZM_ADMIN_AUTH_TOKEN` cookies have the `Secure` attribute set to `true` by default and the `SameSite` Attribute is set to `Lax`(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax) as requested.
=> [CO-191] Cookie Safety

store/src/java-test/com/zimbra/cs/util/proxyconfgen/ProxyConfGenTest.java, store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
The custom template override location that proxyConfGen will  use is set to `/opt/zextras/conf/nginx/templates_custom`
**Config generation flow:** If one or more template overrides are found in the custom templates location(`/opt/zextras/conf/nginx/templates_custom`), the proxyconfgen util will now use those templates to generate the config and will override the default ones that exist in the default template location (`/opt/zextras/conf/nginx/templates`) at the proxyxonfgen step while services start or by manual invocation of the tool.
**Warning header:** A warning header is written to all generated configuration files.
NOTE: The above flow won't work if a custom template path is specified explicitly to the proxyconfgen command using its -t flag. This ensures the backward compatibility …
=> chore: [CO-288] add support for ngnix templates override

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Renamed **carbonioChatsVideoServerRecordingEnabled** attribute into **carbonioVideoServerRecordingEnabled**.
This is made to not link the product name with the ldap attribute directly. So, even if we will decide to change the product name in the future, we can still use the attribute correctly.
Support PR for: https://github.com/Zextras/carbonio-ldap-utilities/pull/10
=> chore: [TEAMS-3737] Renamed video server recording ldap attribute

store/src/java/com/zimbra/cs/util/proxyconfgen/Utils.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebAdminUpstreamAdminClientServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebAdminUpstreamServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebSSLUpstreamClientServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebSSLUpstreamServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebSslUpstreamZxServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebUpstreamClientServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebUpstreamServersVar.java, store/src/java/com/zimbra/cs/util/proxyconfgen/WebUpstreamZxServersVar.java
- prevent duplicate upstream servers in generated nginx conf.
**Test:** 
Manually invoking zmproxyconfgen and generating config from templates skips duplicate entries of upstream servers.
=> fix(proxy): prevent duplicate upstreams

store/conf/attrs/attrs.xml
What has changed:
- These changes will let the proxy use a new set of algorithms while doing TLS/SSL handshake.
- remove explicit TLSV1.3 protocol usage for mailboxd this prevents random handshake failures(SSL alert 80) caused due to issue with jetty on JDK11 (bug JDK-8213202)
=> fix(proxy): [CO-321] server side TLS handshake

store/src/java/com/zimbra/cs/account/ZAttrDomain.java
zimbraAuthFallbackToLocal will default to true when not defined.
Fixes an authentication problem when installing a new infrastructure.
=> fix: zimbraAuthFallbackToLocal default to true when not defined

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
**Key changes:**
- mark FeatureTouchClientEnabled attribute as deprecated
- running the code generator also updated a few defaults we set a few days back for SSL ticket which was also intended but missed for some reasons
=> chore: [CO-333] deprecate FeatureTouchClientEnabled

store/conf/web.xml.production
**Goal:** The servlet is currently set to start when the first request is received. As a result of the startup time and preview processing time, the response to the initial request is delayed by a few more seconds.
**Key changes:** During mailbox startup, PreviewServlet is scheduled to start in the 13th position in the queue.
=> fix: [CO-365] start preview servlet at mailbox boot

Jenkinsfile
This will reduce CI time of a minute or less.
Instead of updating at build time, an agent update would be recommended
My 2 cents to the maven effort
=> chore(CI): jdk11-headless is already included in the agent

common/ivy.xml, common/src/java-test/com/zimbra/common/util/RemoteIPIT.java, common/src/java/com/zimbra/common/util/RemoteIP.java
When OrigIp and OrigPort are not null or the remote address is localhost, remote address and port do not get logged.
In case of requests coming from of a trusted proxy the result is only the client ip and port get logged, but not the proxy server ip and port.
This PRs is to always add remote address and port, except when the remote address is localhost.
=> feat: [CO-378] add proxy ip to log

store/src/java/com/zimbra/cs/service/PreviewServlet.java
add support for nested attachment preview 
ex: now can preview attachments added to an EML sent as attachments in an email :ghost: 
Tests:
- Already covered in existing tests(we just added support for nested part number resolution)
- Manual E2E tests has been done to confirm this addition
=> feat:[CO-422] add support for nested attachment preview

store/src/java-test/com/zimbra/cs/service/admin/ModifyDomainIT.java, store/src/java/com/zimbra/cs/service/admin/ModifyDomain.java
Domain **VirtualHostnames** and **PublicServiceHostname** must be **compliant with domain name**.
**Same rules must apply also for alias domain.**
This PR introduces some checks on virtualHostnames and publicServiceHostname when updating a domain through ModifyDomain.
- validation on publicServiceHostname when given (valid fqdn)
- validation on virtualHostnames when given (valid fqdn)
- **alias domain is treated just a specific type of domain**, so the same API applies. (**missing tests for alias, request them if you believe they are necessary**)
- Compliance error is as follows: "[Field name] must be a valid FQDN and compatible with current domain (or its aliases)".
**Edit: re-requesting review because I forgot to push the validation code for virtualHostnames.**
=> feat: [CO-377] hostname validation

packages/appserver-service/PKGBUILD
Since the package uses pending-setups and service-discover it should depend on them.
In some cases this can lead to errors (was not able to replicate them, but was reported), for example if pending-setups was not installed the package will try to install some files on directories defined by pending-setups.
=> fix(appserver-service): depends service-discover + pending-setups

store/src/java/com/zimbra/cs/account/ZimbraAuthToken.java, store/src/java/com/zimbra/cs/service/account/EndSession.java
The deRegister method of ZimbraAuthToken class has been modified to parse the server_version as empty string if it is null (server_version is always null since we dont set server's server_version property in Carbonio for some reasons).
This string along with other components form a unique dynamic identifier which is used to remove values from account entries in this case for zimbraAuthTokens which is ephermal attribute in nature.
Now, in EndSessionReuqest if logOff attribute is set to true it will properly invalidate the cookie on SOAP servelet and properly delete the AuthToken for the account in directory-server.
**Other changes**
In addition the handle method of EndSession service was refactored and a portion of the method was extracted to new clearAllSessions …
=> fix: [CO-440] properly de-register Account AuthToken in EndSession API

store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java, store/src/java/com/zimbra/cs/util/proxyconfgen/Utils.java
- The domain SSL directory is cleaned to remove orphaned certificate key pair.
**Test:** Changes are manually tested, its really hard to write unit test for this class as
methods and members are static everywhere.
=> fix:[CO-457] delete orphaned cert-key pair from domain SSL dir

store/build.xml, store/conf/localconfig-autogen.xml
When calling generate-rights target from withing **store** module, the task tries to read localconfig under /opt/zextras.
By setting zimbra.config we can tell the class to **load the configuration from a specific file.**
This file contains minimal information: the zimbra_home path (as current directory). The reason is it will load attrs.xml definition defined in it.
These changes were already made in maven migration: https://github.com/Zextras/carbonio-mailbox/commit/6f6ec69f90ab2104bb9f7ae0498f010a21c14317
=> fix: generate rights localconfig

Jenkinsfile.nightly
Add missing copy instruction for maven settings in Nightly builds.
=> chore: [CO-482] copy maven settings file

.gitignore, store/src/main/java/com/zimbra/cs/account/Domain.java, store/src/main/java/com/zimbra/cs/account/ProvUtil.java, store/src/main/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/test/java/com/zimbra/cs/account/MockProvisioning.java, store/src/test/java/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
- Provisioning now sets mailCatchAllForwardingAddress domain attribute to default value during alias domain creation.
=> feat: [CO-477] Set default for 'catch-all messages' address in alias domains

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store-conf/conf/rights/rights-domainadmin.xml, store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java
- new LDAP attribute carbonioLogoUrl added to globalConfig and domain entries
- default value is `https://www.zextras.com`
- attribute is domainInherited,domainInfo and domainAdminModifiable
**LDAP Utils PR**: https://github.com/Zextras/carbonio-ldap-utilities/pull/22
=> feat: [CO-495] add carbonioLogoUrl attribute

store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
Handle Address Book Nginx template files (expand).
- Expand "stream" conf file that will hold stream configurations (example: https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/)
- Expand addressBook template
- Expand ssl and certificates map templates
TODO:
=> chore: [CO-535] Address Book proxyconfgen

soap/src/main/java/com/zimbra/soap/admin/message/CreateDistributionListRequest.java, store/src/main/java/com/zimbra/cs/service/admin/CreateDistributionList.java, store/src/test/java/com/zimbra/cs/service/admin/CreateDistributionListTest.java
- prohibit delegatedAdmins from creating dynamic distribution list using CreateDistributionList SOAP command
- Now throws ServiceException when a delegatedAdmin requests to create dynamic distribution list
=> feat: [CO-526] prevent delegated admins creating DDLs

store/conf/attrs/attrs.xml
**Goal:**
To increase the security and reject false mail from addresses
- set default value to yes for zimbraMtaSmtpdRejectUnlistedRecipient
- postfix SMTP server will reject emails sent to unlisted/unknown addresses(smtpd_reject_unlisted_recipient: yes)
- set default value to yes for zimbraMtaSmtpdRejectUnlistedSender
- postfix SMTP server will reject emails sent by unlisted/unknown addresses (smtpd_reject_unlisted_sender: yes)
- set default value for zimbraMtaSmtpdSenderRestrictions
- set reject_sender_login_mismatch as default value (smtpd_sender_restrictions: +reject_sender_login_mismatch) 
- set default value for zimbraMtaSmtpdSenderLoginMaps
- set default to ldap sender_login_mismatch lookup table (smtpd_sender_login_maps: + …
=> feat: [CO-513] Set sane defaults for postfix smtp server

store/conf/attrs/attrs.xml
- update enum values to limit support to https & redirect mode only
_For more info refer jira CO-551_
**Other PRs:**
- https://github.com/Zextras/carbonio-build/pull/38
- https://github.com/Zextras/carbonio-core-utils/pull/32
=> chore: [CO-551] Update zimbraReverseProxyMailMode attribute

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
- Remove both and mixed mode template expansion
- mixed and both mode templates are no longer required
- update default value of zimbraReverseProxyMailMode to https from both mode
- source code generation (this also includes updates we missed in #151 & #152)
**Realted PRs:**
- https://github.com/Zextras/carbonio-nginx-conf/pull/46
=> feat: [CO-499] Remove both and mixed mode form web proxy config

store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java, store/src/test/java/com/zimbra/cs/account/MockProvisioning.java, store/src/test/java/com/zimbra/cs/service/admin/ModifyDomainIT.java
When using zmprov we want to remove all virtual hostnames on a domain by executing:
> zmprov md <domain_name> zimbraVirtualHostname ""
> 
and not having to remove them all by specifying each one.
This PR adds the fix by matching the expected behavior.
If zimbraVirtualHostname are not passed then existing values will not be overridden, **the condition for removal is met when you pass exactly a zimbraVirtualHostname array containing only the empty string.**
I found MockProvisioning has many limitations as it does not reflect the real underlying behavior of the production system in some cases.
For example removing an attribute by setting it to empty value did not work (it should AFAIK), so I changed the class to match real-scenario.
Code aside, **tested on a VM using zmprov.**
=> fix: [CO-544] modify domain remove vhost names

store/src/main/java/com/zimbra/cs/service/mail/ParseMimeMessage.java, store/src/test/java/com/zimbra/cs/service/mail/ParseMimeMessageTest.java
- fix mime-parsing logic by correctly order mime parts in multi-mime part component of invite email
- mime part with content-type text/plain are placed at top in multi-mime parts with content-type mimepart/alternatives in calendar invite emails
- general code cleanup
=> fix: [CO-553] Calendar invites parsing in Outlook

store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java
- fix existing headers
- add X-Frame-Options for backward compatibility
- add rules to enforce CSP 
**Other PRs:**
- https://github.com/Zextras/carbonio-ldap-utilities/pull/30
- https://github.com/Zextras/carbonio-nginx-conf/pull/50
=> feat: [CO-536] Add/update CSP headers in ReverseProxyResponseHeaders  

soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java, store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java, store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java, store/src/test/java/com/zimbra/cs/rmgmt/RemoteCertbotTest.java, store/src/test/java/com/zimbra/cs/service/admin/IssueCertTest.java
What's changed: 
I've removed "expand" flag from the request (was needed to understand if domain admin asking to issue a new LE cert bcz a virtual host name was added or deleted from the domain) - instead we will always use **--cert-name** as it gives more control over the certificate (will be automaticlly checked by certbot if the cert is needed to be modified somehow. If all argumenets mathches it will keep existing cert if it's still valid othervise would modify existing cert as needed (add or remove VHN or modify public service host name if it was changed). Certbot will store a cert under working directory with the domain name passed with **--cert-name** so it could be easily found and understood to which domain cert belongs to.
So the flow is:
1) admin requests a certficate => 
2) …
=> feat: [CO-619] store Let's encrypt certs to LDAP before proxy conf generation 

store/conf/attrs/attrs.xml
- make carbonioNotificationRecipients and carbonioNotificationFrom inherit from global config
We missed this in the [CO-539], as it was not asked in the requirements, but it makes sense to have the domain entries inherit value from global config if they don't have these two attributes set.
This change requires no migration as 23.4.0 is not yet released.
=> feat: [CO-643] Make Carbonio NotificationRecipients/From domainInherited

packages/appserver-service/PKGBUILD, packages/appserver-service/carbonio-mailbox, packages/appserver-service/carbonio-mailbox-setup.sh, packages/appserver-service/carbonio-mailbox-sidecar.service, packages/appserver-service/intentions.json, packages/appserver-service/policies.json, packages/appserver-service/service-protocol.json
Uniforms mailbox service registration to: https://github.com/Zextras/consul-templates/tree/main/services-package
Tests:
- installation ok
- setup ok
- token is now under /etc/carbonio/mailbox/service-discover/token
**- copy old token to new in postinst. This in case other services are restarted and need the new token but pending-setups did not run (although that shouldn't happen, the token should be read only by the service itself, I'm a bit confused about this)**
- old token /etc/zextras/carbonio-mailbox/token still present in the system (any idea how we can remove it? automatically or manually?)
=> chore: [CO-644] mailbox service-discover registration

packages/appserver-service/carbonio-mailbox
While running pending-setups without old token I found it failed because of chmod and chown pointing to wrong path.
Sorry :pray:
=> chore: [CO-644] chown + chmod new service-discover token

store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyCompressionServerVar.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java, store/src/test/java/com/zimbra/cs/util/proxyconfgen/ProxyCompressionServerVarTest.java
- provide ProxyConfGen variable that can be expanded using templates based on HttpCompressionEnabled server and global config attribute
- proxy.http.compression can be exploded using carbonio-proxy-templates to enable compression
- https://github.com/Zextras/carbonio-nginx-conf/pull/51
- https://github.com/Zextras/carbonio-jetty-conf/pull/6
=> feat: [CO-620] Enable gzip and brotli compression with ProxyConfGen

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java
- added new attribute **carbonioAmavisDisableVirusCheck** which will let us enable/disable antivirus scanning in amavis 
- https://github.com/Zextras/carbonio-amavis/pull/4
=> feat: [CO-659] add attribute to disable the amavis antivirus scan

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store-conf/conf/rights/rights-domainadmin.xml, store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/main/java/com/zimbra/cs/account/ZAttrCos.java
Adds:
- carbonioFeatureMeetingEnabled
- carbonioFeatureTeamEnabled
Redefines as new attribute:
- carbonioFeatureChatsEnabled
This will cause in installation having value at TRUE to be FALSE (wanted behavior)
See also: 
- https://github.com/Zextras/carbonio-ldap-utilities/pull/33
- https://github.com/Zextras/carbonio-build/pull/49
=> feat: [CO-640] chats, meeting, team feature enabled attributes

.release-it.json, Jenkinsfile
**TAG options from CI does not work properly**, because on checkout it does not get all commit history, thus making changelog not working. **I propose to remove it to avoid accidents.**
Since we do the release "manually" another tool, what is left is "release-it" config to automate:
- version bump
- CHANGELOG
- push
The flow of release will be in future, roughly: 
- merge devel to main
- create release branch + execute release-it
- merge release branch into main
- TAG
- Build tag
- Merge main to devel
=> chore: remove tag from CI

store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
- proxyconfgen adds nginx conf for web.clamav.signature.provider service
- https://github.com/Zextras/carbonio-nginx-conf/pull/57
- https://bitbucket.org/zextras/carbonio-thirds/pull-requests/19
=> feat: [CO-665] add web.clamav.signature.provider template

store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
Remove obsolete templates files expansion
- https://github.com/Zextras/carbonio-mailbox/pull/207
- https://github.com/Zextras/carbonio-nginx-conf/pull/63
- https://github.com/Zextras/carbonio-jetty-conf/pull/8
=> chore: [CO-476] remove obsolete proxy template files 

store/conf/web.xml, store/conf/web.xml.production
- this enables asynchronous processing of HTTP requests.
In this particular case NoOpRequests were failing due to missing async support on this filter added [here](https://github.com/Zextras/carbonio-mailbox/pull/167/files#diff-9ded4d1dc53a47fff734d8bc22e5ca1a95d1454482e9b74cee20d30d69bb528cR18).
**For more details refer:** CO-695 on jira.
=> fix: [CO-695] enable async support in guice servlet filter

store/src/main/java/com/zimbra/cs/mailbox/MailSender.java, store/src/test/java/com/zimbra/cs/mailbox/MailSenderIT.java
This fixes a behavior where an email sent as delegated account is left on status "unread" when in Sent folder of delegated account.
This fix makes the email status always "read".
Added IT test to check authenticated user Sent folder is empty, delegated account has Sent size 1, no unread.
This tests covers the behavior with default value of zimbraPrefDelegatedSendSaveTarget = "owner".
It means the sent email should be saved only on delegated account Sent folder.
=> fix: [CO-690] delegated account sent mail always read

Jenkinsfile
SonarQube was introduced in #213 . 
Unfortunately running CI with Skip tests or Skip Sonar does not skip sonar analysis.
- fix the condition so when either skip tests or sonar as flagged, sonar analysis is not executed.
- update params description
=> chore: sonarqube execution

store/src/main/java/com/zimbra/cs/service/admin/AdminAccessControl.java, store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java, store/src/test/java/com/zimbra/cs/service/admin/ModifyDomainIT.java
Now global admin and delegated admin with granted right `modifyGlobalConfig` could set an arbitrary value for zimbraPublicServiceHostname and zimbraVirtualHostname.
=> feat: [CO-675] Let admin set arbitrary PublicService & Virtual hostname

.pre-commit-config.yaml
config now excludes the following file patterns from being processed by pre-commit hooks:
- exclude ZAttr*.java
- exclude attrs.xml
- exclude rights-*.xml
=> chore: pre-commit exclude generated files

pom.xml, store/pom.xml
Check: https://mvnrepository.com/artifact/org.dom4j/dom4j
Fixes this vulnerability: https://github.com/Zextras/carbonio-mailbox/security/dependabot/94
Related PR: https://github.com/Zextras/carbonio-zcs-lib/pull/17
=> chore: bump dom4j to 2.1.4

store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java
- deault globalConf value for reverseProxyMailMode as 'redirect'
**Other PRs:**
- https://github.com/Zextras/carbonio-ldap-utilities/pull/49
See, CO-729 for context.
=> feat: [CO-729] Redirect as default globalConf value for reverseProxyMailMode

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/main/java/com/zimbra/cs/account/AttributeManagerUtil.java
**Note:** This is part 2 of contineous optimization of AttributeManagerUtil, changes in part 1 were merged by this PR  [here](https://github.com/Zextras/carbonio-mailbox/pull/230) 
- remove static from enums as they are static by default
- mark methods override where required
- remove bogus access modifiers from enum constructors
- avoid redundant default parameter assignment for some fields
- minor code cleanup
**Tests:**
- smoke test on dev env
- generated ldiff files with new code has no diffs with old one
=> chore: [CO-723] fix code smells in generated code (Attribute classes)

pom.xml
FilesClient is built on top commons-io 2.11.0. Mailbox ships 1.4, resulting in a runtime error (method not found).
Tested on a VM along with packages of zcs-lib.
=> fix(CO-728): use commons-io 2.11.0

store-conf/conf/log4j.properties.production
This will fix error messages within `/opt/zextras/log/zmmailboxd.out`
```
[3.545s][info][gc] GC(2) Pause Young (Concurrent Start) (Metadata GC Threshold) 87M->56M(3942M) 9.255ms
[3.546s][info][gc] GC(3) Concurrent Mark Cycle
[3.574s][info][gc] GC(3) Pause Remark 58M->58M(3942M) 3.069ms
[3.583s][info][gc] GC(3) Pause Cleanup 58M->58M(3942M) 0.245ms
[3.590s][info][gc] GC(3) Concurrent Mark Cycle 44.796ms
log4j:ERROR Could not find value for key log4j.appender.EWS
log4j:ERROR Could not instantiate appender named "EWS".
log4j:ERROR Could not find value for key log4j.appender.EWS
log4j:ERROR Could not instantiate appender named "EWS".
log4j:ERROR Could not find value for key log4j.appender.EWS
log4j:ERROR Could not instantiate appender named "EWS".
[4.429s][info][gc] GC(4) Pause Young (Prepare …
```
=> fix: log4j.properties: remove undefined references to EWS logger

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java, store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
- CSP header can be set separately.
- ProxyConfGen util will combine the 'Custom response headers' with 'CSP header' to produce complete Response header set.
- Updated CSP policy according to our requirements.
**Other PRs:**
- https://github.com/zextras/carbonio-ldap-utilities/pull/51
=> feat: [CO-756] Update defaults for proxy CSP header

.markdownlint.yaml, .pre-commit-config.yaml
Basically with @federicorispo and @nomanAli95 on behalf of the backend tribe we decided new common rules for `pre-commit` hooks. With this PR, we update the mailbox to these new rules (a document is being prepared with pre-defined templates to copy from, this is basically one of them)
I didn't activate reuse because it runs on all the codebase and makes the build fail. We have to fix our headers before being able to activate it!
=> chore: upgrade pre-commit to new common rules

ant-build-common.xml, pom.xml, store/pom.xml, store/src/main/java/com/zimbra/cs/service/mail/SendMsg.java, store/src/test/java/com/zimbra/cs/account/MockProvisioning.java, store/src/test/java/com/zimbra/cs/service/mail/SendMsgIT.java
Delete draft always from authed user's mailbox when sending an email.
This because when sending an email with a shared mailbox, the Draft is saved by the client on the authed user's mailbox.
It is a temporary fix for the **issue of not deleting the draft when acting as shared account** until we come up with a better flow.
Changes:
- bump to 23.7.1 (PKGBUILD + CHANGELOG in another PR to not lose commit after squash)
- fix behavior + integration test with GreenMail
- test: draft deleted from authed user's mailbox
- test: draft not deleted from shared user's mailbox
=> fix(CO-782): Delete Draft from authed user's mailbox in SendMsg

common/pom.xml
* there was a junit dependency with RELEASE version not resolvable by ivy
=> chore: remove old junit

common/src/main/java/com/zimbra/common/util/ZimbraLog.java
This modification addresses the initialization of the console appender logger utilized by certain CLI utilities that rely on the ZimbraLog class for logging purposes. Change translates the old log4 properties to log4j 2.
=> fix: Log4j properties in ZimbraLog

store/src/main/java/com/zimbra/cs/service/formatter/ArchiveFormatter.java
- StringBuilder object used to accumulate some "extra" user data is initialized instead of being assigned to null avoiding NPE in successive calls.
=> fix: [CO-803] Fix NPE while exporting user data in tgz format

store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java, store/src/test/java/com/zimbra/cs/service/admin/IssueCertTest.java
issueCert api will be available for global admins, domain admins (on their domains) and delegated admin with setDomainAdminDomainAttrs right (instead of getDomain right).
=> chore: [CO-739] limit LE certificate management for delegated admins

common/src/main/java/com/zimbra/common/localconfig/LC.java, packages/common-appserver-conf/PKGBUILD
- update `mailboxd_java_options` in `LC.java` to allow reflection access at runtime **(this ships update in fresh installs)**
- update `mailboxd_java_options` in `LC.java` adding `java.security.egd` to use `file:/dev/./urandom` as SecureRandom source
- post-upgrade scripts were added to carbonio-common-appserver-conf package to handle the update of `mailboxd_java_options` **(this ships update on existing installs)**
=> feat: [CO-807] update mailboxd_java_options for JDK17

store/src/main/java/com/zimbra/cs/mailbox/calendar/cache/CacheToXML.java, store/src/test/java/com/zimbra/cs/mailbox/MailboxTestUtil.java, store/src/test/java/com/zimbra/cs/service/mail/SearchTest.java, store/src/test/resources/com/zimbra/cs/service/mail/CO-831-CalendarAppointmentRequest.json, store/src/test/resources/com/zimbra/cs/service/mail/CO-831-CalendarSearchRequest.json
The field ridZ is missing from SearchResponse when making a SearchRequest for appointments.
The bug was introduced in: 0a265ebd7ba819ab3d04e4ef41dd7db07113870e
This breaks the UI.
I have added a test to create the appointment and call a search. Requests body were taken directly from affected Carbonio instances for simplicity with some changes in user of course.
=> fix: [CO-831] ridZ field missing in SearchRequest of Calendars

store/conf/attrs/attrs.xml, store/ldap/src/updates/attrs/1694605275.json, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java
- added 127.0.0.1 as default value in globalConf for zimbraMailTrustedIP
- provide migration
=> feat: [CO-824] add 127.0.0.1 to MailTrustedIP to prevent loss of OIP

Jenkinsfile, client/pom.xml, common/pom.xml, native/pom.xml, pom.xml, soap/pom.xml, store-conf/pom.xml, store-extra-runtime-dependencies/pom.xml, store/pom.xml
here  reported version is statically set as 'rc'.
Scanning is done on main branch as requested in our meetings (see the ticket for details).
Waiting for suggestion for a better version number usage (maybe retrieved from the pom.xml?)
=> chore: IN-620: use syft and dependency-track platform for SBOM

store-conf/conf/rights/rights-domainadmin.xml, store-conf/conf/rights/rights-domainadmin.xml-template
- set zimbraSSL certificate and private key right on domainAdminRights
Instead of adding these rights to the InitDomain json call it makes more sense to define domainAdminRights as a combo with all the needed rights to avoid confusion.
=> feat: [COR-975] define domain admin rights

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/ldap/src/updates/attrs/1697206170.json, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java
- added `carbonioClamAVReadTimeout` to manage ClamAv socket read timeout in seconds. Attribute is optional in globalConf and server. Is supposed to be used in clamd.conf template.
- https://github.com/zextras/carbonio-mta/pull/8
- https://github.com/zextras/carbonio-ldap-utilities/pull/58
- https://github.com/zextras/carbonio-amavis/pull/7
=> feat: [CO-825] add attribute to manage ClamAv ReadTimeout

store/ldap/src/updates/attrs/1694605275.json
- removed the migration but the default value in new install will still set.
migration was added in [CO-824]
[CO-824]: https://zextras.atlassian.net/browse/CO-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove MailTrustedIP migration

Jenkinsfile, pom.xml
- remove modifier for now, maven not able to handle it
The issue is the pom is published with 23.11.0modifier (modifier is not replaced)
=> fix: maven pom version

store/src/main/java/com/zimbra/cs/mailbox/ContactAutoComplete.java, store/src/main/java/com/zimbra/cs/mailbox/MailSender.java, store/src/test/java/com/zextras/mailbox/util/MailboxTestUtil.java, store/src/test/java/com/zimbra/cs/service/mail/SendMsgTest.java
- a shared account is given access to "/" which is the USER_ROOT, not ROOT folder
=> fix: [CO-851] use USER_ROOT

packages/appserver-db/PKGBUILD
Noticed appserver-db PKGBUILD was not bumped
=> chore: 4.11.1

README.md, soap/ant-generate-soap-docs.xml, soap/pom.xml, store/ant-store.xml, store/pom.xml
To slim down build time we decided to remove few steps:
- Avoid pre-compile (compile twice)
- Avoid generating ZAttr classes automatically (this required pre-compile to call generator classes)
- Avoid generating soap docs. Only WSDL is generated
Added:
- generate BuildInfo class during generate-sources
- in README.md instructions on how to generate rights and ZAttr manually after attrs.xml has been modified (tested)
- in README.md instructions on how to generate soap docs
=> chore: improve build time

packages/common-core-libs/PKGBUILD, pom.xml
This is to prevent multiple bindings for SLF4J, new version of curator-recipes do not bring log4j as dependency.
see: CO-925 for more info.
=> chore: [CO-925] upgrade curator-recipes to 5.5.0

carbonio-jetty-libs/pom.xml, pom.xml, store/pom.xml
- Noticed during tests lots of logs about missing imap-utf-7 which is provided in jetty-libs by zm-charset at runtime (provided) but missing during test executions
=> chore: add zm-charset as test dependency to fix imap-utf-7 warnings

store/src/main/java/com/zimbra/cs/service/admin/SearchDirectory.java, store/src/test/java/com/zimbra/cs/service/admin/SearchDirectoryTest.java
We fixed the behaviour of SearchDirectory command:
- now the 'more' field that tell if there are more pages other than the current is working
- now the 'searchTotal' field provides the correct total items
The current behaviour mimics the one present in the GetQuotaUsage command
=> Fix (CO-933): make SearchDirectory response isMore and searchTotal fields properly work

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/attrs.xml, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/java/com/zimbra/cs/account/ldap/Validators.java, store/src/test/java/com/zimbra/cs/account/ldap/DomainMaxAccountsValidatorTest.java, store/src/test/java/com/zimbra/cs/service/admin/RenameAccountTest.java
- `DomainMaxAccountsValidator` starts validating `zimbraDomainCOSMaxAccounts` and `zimbraDomainFeatureMaxAccounts `for the action rename. Before ServiceException.FAILURE("account object is null", null) was thrown.
=> fix: [CO-856] rename account reports error

common/src/main/java/com/zimbra/common/util/memcached/ZimbraMemcachedClient.java, packages/appserver-store-libs/PKGBUILD, packages/common-core-libs/PKGBUILD, pom.xml, store/src/main/java/com/zimbra/cs/util/ProxyPurgeUtil.java, store/src/test/java/com/zimbra/cs/util/ProxyPurgeUtilTest.java
- use SLF4JLogger logger Implementation for logging spymemcached
- allow overriding LoggerImpl for spymemcached using system property(fallsback to SLF4JLogger if not defined)
- bump spymemcached from version 2.12.1 to 2.12.3
=> fix: [CO-863] Missing log4j class using zmproxypurge

store/ant-store.xml
Since b741b7da317ae988a6a93fc2a7e5fb96e2a39a02 the attrs file location moved and the build reports the log
> [INFO] --- antrun:3.1.0:run (generate-sql-ldap-versions) @ zm-store ---
[INFO] Executing tasks
[INFO]      [echo] Using version 24.2.0_ZEXTRAS_202402
[ERROR]      [exec] Result: 128
[INFO] Executed tasks
>
Fixed this job to fail in case of error + use new path for attrs.xml.
=> fix(attrs-schema): create-version-ldap fails silently with error 128

store/src/main/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/main/java/com/zimbra/cs/account/ldap/SpecialAttrs.java, store/src/main/java/com/zimbra/cs/ldap/LdapUtil.java, store/src/main/java/com/zimbra/cs/service/admin/CreateAccount.java, store/src/test/java/com/zimbra/cs/account/ldap/LdapProvisioningTest.java, store/src/test/java/com/zimbra/cs/ldap/LdapUtilTest.java, store/src/test/java/com/zimbra/cs/service/admin/CreateAccountTest.java
- allow creating account using supplied `zimbraId` in both LDAP and SOAP provisioning
- passed `zimbraId` should be a valid UUID
- if the `zimbraId` is not supplied, a new UUID is generated and used as usual.
=> feat: [COR-936] Create account with given zimbraId

store/pom.xml, store/src/test/java/com/zimbra/cs/db/HSQLDB.java
Add possibility to use some classes in test scenarios.
For now only the in memory database.
The plan is also to add, in future, an in memory ldap with mailbox required data for easier test setup.
In test-jars only minimum required set of classes are included.
=> chore: export HSQLDB class for testing

store/pom.xml
Fix on a9000caa02c58cd04bacf5ffa879d4d96037d1c0 
HSQLDB had nested classes, forgot to include them
=> chore: forgot to include nested classes of HSQLDB

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/main/java/com/zimbra/cs/account/ZAttrCalendarResource.java, store/src/main/java/com/zimbra/cs/account/ZAttrCos.java, store/src/main/java/com/zimbra/cs/account/ZAttrDistributionList.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/java/com/zimbra/cs/account/ZAttrDynamicGroup.java, store/src/main/java/com/zimbra/cs/account/ZAttrServer.java, store/src/main/resources/conf/attrs/attrs.xml
- update outdated information about `userPassword` attribute (we do not use SHA1 to produce password salt. We use Argon2), avoid unnecessary used hashing information in description. 
- minor cleanup in attrs.xml
=> chore: update attributes description

store/ant-store.xml, store/ldap/src/updates/attrs/1710337715.json, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/resources/conf/attrs/attrs.xml
- add `*.jsdelivr.net` in allowed hosts from where web app can load javascripts  
- provide migration to update defaults of carbonioReverseProxyResponseCSPHeader
=> feat:[CO-1008] Update defaults for carbonioReverseProxyResponseCSPHeader attribute

Jenkinsfile
**Motivation:**
We've noticed that during SonarQube scanning, certain autogenerated classes(`**/com/zimbra/cs/account/ZAttr*.java,**/com/zimbra/common/account/ZAttr*.java`) are being included in the analysis. These classes typically contain thousands of lines of Java code and consist mainly of simple getter, setter, and unsetter methods. As these classes are autogenerated and not manually maintained, they don't require scrutiny from SonarQube, and their inclusion in the analysis results in noise and unnecessary reports.
**In this MR:**
We update the CI to exclude these autogenerated classes from SonarQube scanning process. By doing so, we can focus SonarQube's analysis on the code that requires attention and avoid false positives.
=> chore: Exclude generated classes from SonarQube analysis

store/src/test/java/com/zimbra/cs/service/mail/ParseMimeMessageTest.java
Notes:
- these tests were disabled ~2 years ago
- while taking a look at ParseMimeMessage I found its test were disabled and the reason was because they were failing as ParseMimeMessage#parseMimeMsgSoap requires a Msg element WITH a parent (here I chose SendMsgRequest as parent).
Without parent the method throw a nullpointerexception (check line 228 of ParseMimeMessage to see why).
While it is a very odd design for such a method (a method accepting an element that depends on a parent), I would like to re-enable these tests as they can help document this behavior and can help in future refactor avoiding regressions
=> test: re-enable ParseMimeMessageTest

Jenkinsfile
- most of these classes are used through reflection by framework and are setter/getter
=> ci(sonar): exclude SOAP request/reponse classes

common/src/main/java/com/zimbra/common/soap/MailConstants.java, soap/src/main/java/com/zimbra/soap/mail/message/FullAutocompleteRequest.java, soap/src/main/java/com/zimbra/soap/mail/type/AutoCompleteMatch.java, store/src/main/java/com/zimbra/cs/service/mail/FullAutoComplete.java, store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
- A new element `'orderedAccountIds'` was introduced in `FullAutocompleteRequest` . This field is used to specify the accounts from which autocomplete matches will be returned. The order of the account IDs in this field determines the  order in which the macthes are returned in `FullAutocompleteResponse` .
- Enhacned ordering algorithm to return FullAutocomplete matches. The new sorting/ordering and limiting algorithm works as follows:
- Matches from the most preferred source account (the first accountId in 'orderedAccountIds') are given higher priority and are placed on top.
- Matches from other source accounts are sorted primarily based on ranking, followed by alphabetical ordering.
- Duplicate matches are omitted keeping the highest ranked match from both …
=> feat: [CO-982] Enhance ordering of matches in FullAutoComplete

store/src/main/java/com/zimbra/cs/service/mail/FullAutoComplete.java
An imporvement to #487, the response now serialize each match instead of returning them as string.
=> fix: [CO-1047] serialize matches also into JSON objects in FullAutoComplete

packages/directory-server/carbonio-directory-server.target
This is a QA-fix and should be back-merged in devel.
After the merge in main a new tag and version should be forged
=> chore: systemd: make targets able to be enabled at boot

store/src/main/java/com/zimbra/cs/account/AccountServiceException.java, store/src/main/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/test/java/com/zimbra/cs/account/auth/ZimbraCustomAuthTest.java, store/src/test/java/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
- Prevent the CE Auth SOAP API handle recovery token based authentications when Carbonio Auth Mech is enabled. 
- recovery token based authentication can no more allow the user to bypass 2FA or any Auth mechanism enforced by Carbonio auth
- if Carbonio Auth is not registered as Authentication mechanism, i.e Carbonio CE, the Auth API will process recovery token based authentication as usual. 
Depends on: https://github.com/zextras/carbonio-auth/pull/75
=> feat: [CO-985] Enhance recovery code based Auth handling when carbonio auth is registered

store/src/main/java/com/zimbra/cs/service/mail/FullAutoComplete.java, store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
- contact groups (AutoCompleteMatch type `group`) are now also ordered based on their Display name(`display`)
=> feat: [CO-1061] Support Contact groups ordering in FullAutoComplete

soap/src/main/java/com/zimbra/soap/account/message/GetAccountInfoRequest.java, soap/src/main/java/com/zimbra/soap/admin/message/GetAccountInfoRequest.java, store/src/main/java/com/zimbra/cs/account/soap/SoapProvisioning.java, store/src/main/java/com/zimbra/cs/service/account/GetAccountInfo.java, store/src/main/java/com/zimbra/cs/service/admin/GetAccountInfo.java, store/src/test/java/com/zimbra/cs/service/account/GetAccountInfoTest.java, store/src/test/java/com/zimbra/cs/service/admin/GetAccountInfoTest.java
`GetAccountInfo` APIs (admin, user) start returning account status.
=> feat: [CO-1040] make account status accessible via GetAccountInfo SOAP API

store/src/main/java/com/zimbra/cs/filter/jsieve/BulkTest.java, store/src/test/java/com/zimbra/cs/filter/BulkTestTest.java
- update `BulkTest` sieve filter to prevent read-receipt notification mails getting filtered as mass-marketing/bulk mails
=> feat: [CO-959] Filter out read-receipt notification mails from BulkTest Sieve filter

store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
**This is just an attempt to fix the following flaky test in FAC**
```
Failures:
[ERROR] FullAutoCompleteTest.should_return_matches_from_other_preferred_accounts_respecting_account_AutoCompleteMaxResultsLimit:156 expected: <3> but was: <2
```
=> chore: use random data to fix flaky test in FAC

common/src/main/java/com/zimbra/common/soap/MailConstants.java, soap/src/main/java/com/zimbra/soap/mail/type/FolderActionSelector.java, store/pom.xml, store/src/main/java/com/zimbra/cs/mailbox/FolderActionEmptyOpTypes.java, store/src/main/java/com/zimbra/cs/mailbox/Mailbox.java, store/src/main/java/com/zimbra/cs/service/mail/FolderAction.java, store/src/test/java/com/zextras/mailbox/soap/SoapTestSuite.java, store/src/test/java/com/zimbra/cs/service/UserServletTest.java, store/src/test/java/com/zimbra/cs/service/mail/FolderActionTest.java, store/src/test/resources/com/zimbra/cs/service/mail/SampleAppointmentRequest.json
- add new optional attribtute `type` in `FolderActionSelector` for `empty` operation.
This attribute can be passed to the FolderActionRequest.
- add support accepting `type` in emptyFolder to perform empty folder by specified type of item
- minor cleanup and fixes
- add helper method `getSoapContextForAccount` in `SoapTestSuite`
=> feat: [CO-1023] add ability to empty folder by item type

store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/main/resources/conf/attrs/amavisd-new-attrs.xml
:bell: needed by https://github.com/zextras/carbonio-mails-ui/pull/591
=> CO-1133 define amavis white/black list attribute scope

store/src/main/java/com/zimbra/cs/service/UserServlet.java, store/src/main/java/com/zimbra/cs/service/formatter/NativeFormatter.java, store/src/test/java/com/zimbra/cs/mailbox/MailboxTestUtil.java, store/src/test/java/com/zimbra/cs/service/UserServletTest.java, store/src/test/java/com/zimbra/cs/service/formatter/NativeFormatterTest.java
- The UserServlet, which handles `/service/home` requests, now correctly returns XML and various other scriptable attachment MIME parts.
- Scriptable attachments are now dispatched with `content-disposition` of `attachment` header even if requested as `inline`.
- To avoid breaking the content, the defanging logic was removed, so scriptable attachments are no longer defanged before dispatching.
=> fix: [CO-1179] UserServlet to properly return XML and scriptable attachments without defanging

store/src/main/java/com/zimbra/cs/service/mail/FullAutoComplete.java, store/src/test/java/com/zimbra/cs/service/mail/FullAutoCompleteTest.java
**What's changed:**
- add a type-safe builder class `AutoCompleteMatchElementBuilder` to ensure null-safe handling when serializing `AutoCompleteMatch` back to the `Element` class. This prevents NullPointerExceptions (NPEs) in specific types of autocomplete matches, such as Distribution list (GalGroup Match type), which may have some fields uninitialized (null).
- enhanced API resilience: FAC API now returns matches from "other preferred accounts" if the passed "preferred account" does not exist, instead of failing.
=> fix: [CO-1249] Better handling of GalGroup type matches in FullAutoComplete API

store/ldap/conf/ldap/config/cn=config/cn=module{0}.ldif
Seems that adding migrate file is not enough. So I replace the .la module entry directly within ldif file. Let me know if it's a good approach. I don't know ldap technicatlities
Same stuff for carbonio-advanced-lib occurrance
https://github.com/zextras/carbonio-advanced-lib/pull/119
=> chore: use new and builtin argon2 module included in 2.5.x

common/src/main/java/com/zimbra/common/soap/MailConstants.java, soap/src/main/java/com/zimbra/soap/mail/type/EmailAddrInfo.java, store/src/main/java/com/zimbra/cs/service/mail/ModifyCalendarItem.java, store/src/test/java/com/zextras/mailbox/soap/SoapUtils.java, store/src/test/java/com/zextras/mailbox/soap/utils/CreateMountpoint.java, store/src/test/java/com/zimbra/cs/service/mail/ModifyAppointmentApiTest.java, store/src/test/java/com/zimbra/cs/service/mail/ModifyCalendarItemApiTest.java
This bug causes the attendees to not be notified whenever an appointment is updated on a shared calendar.
That are some inner logics that caused this behavior, like trying to detect if the inviteId and the folderId (calendar id) are on the requested mailbox.
However when working on a shared calendar, by referencing a mountpoint, the mailbox proxies the call to the mailbox of the User's shared calendar and fails to correctly identify the folderId is on the correct mailbox. This causes the variable interMboxMove to be updated and in the end the notification is not sent.
Instead of updating the interMboxMove variable we decided to always notify whenever an appointment changes (this design was shared internally)
=> fix: [CO-1239] always notify attendees when appointment is updated

packages/directory-server/PKGBUILD, store/ldap/src/migrations/migrate20240716-UpdatePidFilePath.pl
- add `migrate20240716-UpdatePidFilePath.pl` migration script to apply migration in carbonio-directory-server postinstall upgrade hook.
- script migrates LDAP `olcPidFile` in conf database to `/run/carbonio/slapd.pid` from `/opt/zextras/data/ldap/state/run/slapd.pid`
=> fix: [CO-1358] Migrate the slapd PID file location to new one

common/src/main/java/com/zimbra/common/localconfig/LC.java, packages/mailbox-jar/PKGBUILD, store/src/main/java/com/zimbra/cs/service/account/AccountService.java, store/src/main/java/com/zimbra/cs/service/account/GetAllLocales.java, store/src/main/java/com/zimbra/cs/service/account/GetAvailableLocales.java, store/src/main/java/com/zimbra/cs/service/admin/AdminService.java, store/src/main/java/com/zimbra/cs/service/admin/FlushCache.java, store/src/main/java/com/zimbra/cs/service/admin/GetAllLocales.java, store/src/main/java/com/zimbra/cs/util/WebClientL10nUtil.java, store/src/main/java/com/zimbra/cs/zimlet/ZimletException.java, store/src/main/java/com/zimbra/cs/zimlet/ZimletUtil.java
This reverts commit 7dcd4193241090dea92ea65c635c63cb5ccc4b29.
We found out that actually mailboxd directory still exists, and it is  a symbolic link to /opt/zextras/jetty_base, which is created by the package carbonio-appserver.
We plan to further clean it up in the future as there are still many references to it and in carbonio-bootstrap logic.
=> Revert "refactor: remove mailboxd_directory (#549)"

store/src/main/java/com/zextras/mailbox/LikeXmlJettyServer.java, store/src/test/java/com/zextras/mailbox/SampleLocalMailbox.java
Uses binding address from configuration, as it was on previous standalone jetty
=> chore: use configured bind addresses

packages/appserver-service/carbonio-appserver.service, packages/common-appserver-conf/carbonio-milter.service
**RATIONALE**
zmmailboxd.out log is required by many scripts related to mailbox debug (zmthrdmp for example). These edits are required to have zmmailboxd.out in its right place.
[StandardOutput](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html) usage would be great but this causes the generation of wrong owners (`root` instead of `zextras`) for the referenced file.
Edit:
systemd and zmcontrol will be mutually exclusive. so root user for zmmailboxd.out will make zmthrdump work flawlessly
=> chore: systemd-units: re-enable zmmailboxd.out log and fix milter exit status

store/conf/web.xml
package name in web.xml was not aligned with actual PreviewServlet package name. This makes PreviewServlet fail when deploying from devel
=> fix: fixed PreviewServlet package name in web.xml

store/src/main/java/com/zextras/mailbox/LikeXmlJettyServer.java
This PR fixes the rewrite and access log bugs.
Handlers have been re-arranged to be:
- RewriteHandler
- defaulthandler
- webApp
- requestlog
In case of compression enabled it's the same, except gziphandler is on top of the chain
So rewrites are applied before everything
=> fix: [CO-1441][CO-1443] rewrite handlers

Jenkinsfile, jython-libs/pom.xml, pom.xml
These changes address three issues:
- alignment of jython-libraries module version
- set of profile -pProd or default (devel) depending if building tag or not
- Fix dependencies version using project.version variable, according to: https://maven.apache.org/maven-ci-friendly.html
We noticed that releasing a non SNAPSHOT version produces a pom with SNAPSHOT dependencies, for example zm-mailbox-24.9.1.pom contains zm-common-24.9.1-SNAPSHOT. 
This causes projects using mailbox as dependency will fail downloading transitive dependencies (zm-store-24.9.1-SNAPSHOT does not exist).
Using ${project.version} seems to be the supported way by Maven.
=> fix: versioning

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/main/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/main/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/main/java/com/zimbra/cs/account/ZAttrCos.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/java/com/zimbra/cs/service/FileUploadServlet.java, store/src/main/resources/conf/attrs/attrs.xml, store/src/test/java/com/zimbra/cs/service/FileUploadServletTest.java
- `FileUploadServlet` maxsize 0 now mean unlimited. This aligns the behavior of `zimbraFileUploadMaxSizePerFile` with `zimbraMtaMaxMessageSize`.
- update description of zimbraFileUploadMaxSizePerFile attribute to reflect the updated information.
=> feat: [CO-1481] FileUploadServlet, Align maxSize calculation 

store/src/main/java/com/zimbra/cs/service/AttachmentService.java, store/src/main/java/com/zimbra/cs/service/MailboxAttachmentService.java, store/src/main/java/com/zimbra/cs/service/servlet/preview/PreviewHandler.java, store/src/main/java/com/zimbra/cs/service/servlet/preview/PreviewServlet.java, store/src/test/java/com/zimbra/cs/service/MailboxAttachmentServiceTest.java, store/src/test/java/com/zimbra/cs/service/servlet/preview/PreviewHandlerTest.java
- `MailboxAttachmentService` has new method called `getAttachmentByItemId` which takes `ItemId` object and allows retrieving attachments from appointments as well as emails `MailItem` types.
- `PreviewHandler` now uses `MailboxAttachmentService::getAttachmentByItemId` to handle previewing attachments from appointments as well.
- https://github.com/zextras/carbonio-calendars-ui/pull/505
=> feat: [CO-1528] PreviewServlet allow previewing attachments from Appointments

store/pom.xml
Charset dependency is needed at runtime in order to handle special characters, such as cyrillic alphabet.
See: https://github.com/zextras/carbonio-charset
=> hotfix: [CO-1529] add charset dependency

store/src/main/java/com/zimbra/cs/account/callback/AccountStatus.java, store/src/main/java/com/zimbra/cs/service/admin/AdminService.java, store/src/main/java/com/zimbra/cs/service/admin/DeleteAccount.java
- Message broker is now optional and nothing crashes if it isn't reachable
Refs: CO-1552
=> fix: make message broker optional

common/src/main/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/main/java/com/zimbra/cs/account/SearchDirectoryOptions.java, store/src/main/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/main/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/main/resources/conf/attrs/attrs.xml, store/src/test/java/com/zimbra/cs/account/AttributeManagerTest.java
**Feature Update:**
This update enables searching for users within specified domains, available exclusively in Carbonio (not in CE).
**Changes Made:**
**_New Attribute Added:_** `carbonioSearchSpecifiedDomainsByFeature`
This attribute was introduced to allow conditional search behavior based on feature availability in Carbonio.
**_Modified Search Directory Options_:**
Updated SearchDirectoryOptions to support setting multiple search bases in LDAP, enhancing flexibility in user directory searches.
=>  feat: [CO-1513] Search users in specified domains by feature (carbonio-advanced)

store/src/main/java/com/zextras/mailbox/messageBroker/CreateMessageBrokerException.java, store/src/main/java/com/zextras/mailbox/messageBroker/MessageBrokerFactory.java, store/src/main/java/com/zimbra/cs/account/callback/AccountStatus.java, store/src/main/java/com/zimbra/cs/service/admin/AdminService.java, store/src/main/java/com/zimbra/cs/service/admin/DeleteAccount.java, store/src/test/java/com/zextras/mailbox/callbacks/AccountStatusChangedCallbackTest.java, store/src/test/java/com/zextras/mailbox/messageBroker/MessageBrokerFactoryTest.java, store/src/test/java/com/zextras/mailbox/util/MailboxTestUtil.java, store/src/test/java/com/zimbra/cs/service/admin/AdminServiceWithFakeBrokerClient.java, store/src/test/java/com/zimbra/cs/service/admin/DeleteAccountTest.java
When installing Carbonio, during bootstrap, instantiation of DeleteAccount fails, causing Mailbox to not start properly (Jetty: UNAVAILABLE) because consul token (and Consul) are not installed/available yet.
Consul and Consul tokens are available only after bootstrap, so we made the SOAP layer (Admin, DeleteAccount API) to "loosely" depend on the message broker client (opted for a Try)
=> fix: DeleteAccount fails mailbox startup during bootstrap causing installation to be stuck

store/src/main/java/com/zimbra/cs/service/mail/message/parser/ParseMimeMessage.java, store/src/test/java/com/zimbra/cs/service/mail/message/parser/ParseMimeMessageTest.java
Attachments to messages have a suggested filename for browsers, except for attached emails.
This PR adds a filename using the original email subject.
=> feat(CO-1264): set attachment filename on attached emails

packages/appserver-service/carbonio-mailbox-policies.json, pom.xml, store/src/main/java/com/zextras/mailbox/account/usecase/DeleteUserUseCase.java, store/src/main/java/com/zextras/mailbox/client/ServiceDiscoverHttpClient.java, store/src/main/java/com/zextras/mailbox/messageBroker/MessageBrokerFactory.java, store/src/main/java/com/zextras/mailbox/messageBroker/consumers/DeletedUserFilesConsumer.java, store/src/main/java/com/zimbra/cs/service/admin/AdminService.java, store/src/main/java/com/zimbra/cs/service/admin/DeleteAccount.java, store/src/test/java/com/zextras/mailbox/messageBroker/MessageBrokerFactoryTest.java, store/src/test/java/com/zimbra/cs/account/ProvUtilTest.java, store/src/test/java/com/zimbra/cs/service/admin/DeleteAccountTest.java
- Added a message broker consumer for a confirmation event emitted by files once blobs are deleted from powerstore
- Updated service discover client to get if a service is installed on current infrastructure
- Now the delete account operation, if files is installed, does not immediatly delete an account: the real deletion will happen after consumer receives the confirmation event
Refs: CO-1720
=> fix: [CO-1720] delete account from mailbox only after files finished deleting blobs from powerstore

store/src/main/java/com/zextras/mailbox/messageBroker/CreateMessageBrokerException.java, store/src/main/java/com/zextras/mailbox/messageBroker/MessageBrokerFactory.java, store/src/main/java/com/zimbra/cs/service/admin/AdminService.java, store/src/main/java/com/zimbra/cs/service/admin/DeleteAccount.java, store/src/test/java/com/zimbra/cs/service/admin/DeleteAccountTest.java
- MessageBrokerClientFactory now returns a MessageBrokerClient that is working and healthy (added generic exception handler to catch runtimes and add healthcheck call)
- DeletedUserFilesConsumer init will now be retried if it fails to handle message broker downtime on boot
- MessageBrokerClient is now created for each publish event request to handle a permanently broker client if initialized and passed on boot while message broker was down
Refs: CO-1757
=> fix: retry consumer init if failed and handle message broker factory exceptions

packages/appserver-service/carbonio-mailbox-policies.json
- this will result in files to appear as "not installed" to mailbox, so no delete event is published during account delete and the user will be immediately deleted
=> fix: [CO-1783] remove mailbox permission to access files healthcheck

store/src/main/java/com/zextras/mailbox/MailboxAPIs.java
While converting web.xml to servlets I found some static ports were configured statically in the original web.xml, in addition to dinamically configured ports coming from LDAP attributes. 
These values are used to determine which API calls are accepted based on port.
For example, while the standard soap servlet technically binds also at adminPort, it cannot receive any request on it, because allowed ports is only mailPort + mailSSLPort and not adminPort. This logic is managed by the parameter "allowed.ports", defined in the parent class ZimbraServlet. 
The static allowed ports are:
- 7071, 7073, 7070, 7443
Since Mailbox binds only on ports defined in LDAP config, these static values are not needed. 
While extracting the ports into variables I was able to classify mailbox APIs in these …
=> refactor: [CO-1826] classify and give mailbox ports a proper name

common/src/main/java/com/zimbra/common/localconfig/LC.java, store/src/main/java/com/zimbra/cs/imap/ImapSearch.java, store/src/test/java/com/zimbra/cs/imap/ImapSearchTest.java
* Back merge of https://github.com/Zimbra/zm-mailbox/commit/893158f277aefd089bbe466eaee8377606681357
=> fix: [CO-1848] skip imap UI id range search

client/pom.xml, common/pom.xml, pom.xml, soap/pom.xml
- remove jacoco and custom surefire configuration from client, soap and common modules (enables parallel testing on these modules)
- bump easymock to 5.2.0 to avoid reflection issues (jdk 17+ compatibility)
=> test: run soap, client and common tests in parallel

client/pom.xml, common/pom.xml, pom.xml, soap/pom.xml
Just checking if Sonar is using the default jacoco path to collect coverage or is using junit.xml reports.
Note from the CI:
'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
So by default it uses target/site/jacoco/jacoico.xml, hence Jacoco is mandatory to collect coverage
=> chore: check jacoco coverage

store/ant-store.xml
- causes NumberFormatException (For input string: ""0")
=> fix: remove quote from buildInfo.properties microversion

docker/standalone/docker-compose.yaml
During the initialization of the OpenLDAP Docker container, the service failed with the following error:
```
ch_calloc of 1073741816 elems of 664 bytes failed  
slapd: ch_malloc.c:107: ch_calloc: Assertion '0' failed
```
The issue was due to memory allocation limits. After adjusting the container's ulimit settings, the slapd service started successfully.
I'm using Ubuntu 24.10
Regards
M
=> OpenLDAP service startup failure in the Docker container

docker/standalone/docker-compose.yaml, docker/standalone/mailbox/entrypoint.sh
Makes mailbox container available/autodiscovered for reverse proxy when used with https://github.com/zextras/carbonio-proxy/ container
=> chore: register carbonio mailbox container as available for proxy

Jenkinsfile
Kept container definition for testing purposes in this repo, but the real container used for development is defined here: https://github.com/zextras/carbonio-mta/pull/27
=> chore: do not publish MTA container

Jenkinsfile
This PR updates the Jenkins pipeline to use the newly released jenkins-packages-build-library v1.0.0, which introduces major improvements to our build infrastructure:
Key Benefits:
1. reduce duplicated code
2. centralized configuration for supported platforms (ubuntu-jammy, ubuntu-noble etc.)
3. reutilize the playground rt project to test the pipeline release flow
These changes significantly reduce pipeline complexity while making builds more maintainable and reliable across all Zextras repositories.
=> chore (ci): upgrade to jenkins-packages-build-library@1.0.0

docker/standalone/mailbox/Dockerfile, docker/standalone/mailbox/description.md, docker/standalone/mailbox/entrypoint.sh
Allows collecting traces from the mailbox.
Doesn't start with the agent if no tracing options provided (else causes nasty but non-harmful stack traces in logs)
=> chore: [CO-2521] add opentelemetry java agent and tracing options to container

store/src/main/java/com/zimbra/cs/account/LdapAttributeInfo.java, store/src/main/java/com/zimbra/cs/account/ldap/LdapAttributeCallbackHelper.java, store/src/test/java/com/zimbra/cs/account/LdapAttributeInfoTest.java
Noticed some logs trying to instantiate a class when no callback exist on the attribute
=> fix: avoid loading callback for attributes that don't have a callback

Jenkinsfile
* Updated the library identifier to version 1.0.4
* Changed method signature from 'def' to 'void' for mvnCmd.
* Simplified isBuildingTag method.
* Improved formatting and consistency in environment variables and parameters.
* Remove unnecessary mvnProfile function.
* Directly use BUILD_PROPERTIES_PARAMS in Maven commands.
* Adjust profile selection logic for publishing to Maven.
=> chore(ci): update jenkins-packages-build-library to 1.0.4

docker/standalone/mailbox/Dockerfile, docker/standalone/mailbox/description.md, docker/standalone/mailbox/entrypoint.sh
Proposing a parameter to override some startup options of the mailbox.
There are many things that can be overridden, I decided to start from the memory since we have a use case for it.
=> chore: allow overriding certain options of mailbox container on startup
